# Generated by Django 5.0.6 on 2024-06-25 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogpage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="draft",
                max_length=10,
            ),
        ),
    ]
